active:
  artifact: data/models/production.joblib
  config: models/production/log_fs_e75_f20_00.yaml
  filters:
    circuit:
    - tour
    - chal
    draw_type: singles
  train_date_range:
    end: '2024-12-31'
    start: '2020-01-01'
  trained_at: '2026-03-10T22:44:40.508132+00:00'
voters: []
history: []
