data:
  date_range:
    end: 2025-12-31
    start: 2020-01-01
  filters:
    circuit:
    - tour
    - chal
    draw_type: singles
features:
  include:
  - player_glicko_diff_over_sigma_sum
  - opp_tourn_matches_won
  - player_tourn_matches_won
  - player_elo_surface_diff
  - player_days_since_surface
  - opp_days_since_surface
  - player_losses_vs_surface_specialists
  - opp_losses_vs_surface_specialists
  - round_ordinal
  - player_age
  - opp_age
  - opp_deciding_set_pct
  - player_deciding_set_pct
  - player_iid_hold_prob(days=15)
  - opp_iid_hold_prob(days=15)
  - player_glicko_rd
  - opp_glicko_rd
  - player_venue_win_pct
  - opp_venue_win_pct
  - player_opp_elo_faced_avg(days=365)
  - opp_opp_elo_faced_avg(days=365)
  - player_iid_hold_prob(days=180)
  - opp_iid_hold_prob(days=180)
  - player_surface_pts_service_won_pct(days=180)
  - opp_surface_pts_service_won_pct(days=180)
metrics:
  primary: log_loss
model:
  params:
    colsample_bylevel: 0.8358212622413465
    colsample_bynode: 0.8322042350838024
    colsample_bytree: 0.7119996702425103
    gamma: 1.4338486123158651
    learning_rate: 0.09684407393915145
    max_delta_step: 2
    max_depth: 3
    min_child_weight: 2
    n_estimators: 900
    reg_alpha: 0.5772337521277121
    reg_lambda: 1.4422812809102614
    scale_pos_weight: 1.0273441227584303
    subsample: 0.987434310586901
    n_jobs: 8
    random_state: 42
  type: xgboost
validation:
  test_months: 12
  train_months: 24
  type: date_sliding
calibration:
  method: asymm_isotonic
  lambda_over: 1.05
