"""Feature definitions for the model platform.

This module auto-discovers and imports all feature modules in this package,
which registers the features via decorators.
"""

# Import all feature modules to trigger registration
from mvp.model.features import (
    context,
    elo,
    fitness,
    form,
    glicko,
    glicko_interactions,
    h2h,
    iid,
    points,
    quality,
    ranking,
    returns,
    score_depth,
    serve,
    static,
    style,
    style_history,
    style_matchup,
    style_matchup_retrieval,
    style_radar,
    surface,
    tiebreak,
    tier,
    tournament,
    tournament_points,
    transition,
    volatility,
    win_rate,
)
from mvp.model.registry import get_registry

__all__ = [
    "get_registry",
    "context",
    "elo",
    "fitness",
    "form",
    "glicko",
    "glicko_interactions",
    "h2h",
    "iid",
    "points",
    "quality",
    "ranking",
    "returns",
    "score_depth",
    "serve",
    "static",
    "style",
    "style_history",
    "style_matchup",
    "style_matchup_retrieval",
    "style_radar",
    "surface",
    "tiebreak",
    "tier",
    "tournament",
    "tournament_points",
    "transition",
    "volatility",
    "win_rate",
]
